name: terracotta
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.12b0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.0.4
  - ca-certificates=2021.10.8
  - cffi=1.15.0
  - cfgv=3.3.1
  - cfitsio=4.0.0
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask-core=2021.12.0
  - dataclasses=0.8
  - decorator=5.1.0
  - distlib=0.3.4
  - editdistance-s=1.0.0
  - filelock=3.4.0
  - freetype=2.10.4
  - fsspec=2021.11.1
  - giflib=5.2.1
  - icu=67.1
  - identify=2.3.7
  - imagecodecs=2021.11.20
  - imageio=2.13.3
  - ipython=7.30.1
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9d
  - jxrlib=1.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.3
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - networkx=2.3
  - nodeenv=1.6.0
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - platformdirs=2.3.0
  - pre-commit=2.16.0
  - prompt-toolkit=3.0.24
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyparsing=3.0.6
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pywavelets=1.2.0
  - pyyaml=6.0
  - readline=8.1
  - scikit-image=0.19.1
  - scipy=1.7.3
  - setuptools=59.4.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.37.0
  - tifffile=2021.11.2
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.5.1
  - typing_extensions=4.0.1
  - virtualenv=20.4.7
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - affine==2.3.0
    - apispec==5.1.1
    - apispec-webframeworks==0.5.2
    - attrs==21.2.0
    - cachetools==4.2.4
    - click==7.1.2
    - click-plugins==1.1.1
    - click-spinner==0.1.10
    - cligj==0.7.2
    - flask==2.0.2
    - flask-cors==3.0.10
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - markupsafe==2.0.1
    - marshmallow==3.14.1
    - mercantile==1.2.1
    - rasterio==1.1.8
    - shapely==1.8.0
    - snuggs==1.4.7
    - tqdm==4.62.3
    - werkzeug==2.0.2
